### PR TITLE
meson: Fix warnings with more recent version of meson

### PR DESCRIPTION
**Pull request by xclaesse**

### CODE REVIEW

**Comment by xclaesse** [comment]
@nirbheek it would be great to make a release tarball with this, so we can use local tarballs in glib CI instead of cloning the git repository.

**Comment by nirbheek** [comment]
Done: https://github.com/centricular/libffi/releases/tag/3.2.9999

I used a different naming scheme than upstream, and a version that's lower than the latest upstream because we're behind libffi/master right now.

**Comment by xclaesse** [comment]
That's why I really think we should use my 'external-project' PR so we can stop maintaining outdated forks.

**Comment by xclaesse** [comment]
btw, any reason this is not in wrapdb ?

**Comment by nirbheek** [comment]
> That's why I really think we should use my 'external-project' PR so we can stop maintaining outdated forks.

I really don't understand why you keep saying that the external-project PR somehow excludes writing and maintaining meson build files. It's actually kind of annoying. The purposes of the two are very different.

If the project uses Autotools, you cannot build with MSVC. If it uses CMake (with MSVC support), you need something more than the very basic support your PR adds because you need to match the CRT type, toolset versions, and so on.

If your project uses C++ and you're on Windows, using a uniform build system is even more important because the C++ ABI is not the same between MSVC and GCC/Clang and is also different across different C++ stds.

Also, as we've learned with Cerbero, projects that use Autotools often require *specific versions* of a lot of ancillary build tools to function well (gettext, automake, autoconf, m4, perl, etc), which just make a meson-subproject setup completely unworkable outside of Linux (unless you use MSYS2 or Homebrew).

There are a lot of edge cases that need to be taken care of when building on any platform other than Linux. F.ex., for iOS if you want to enable bitcode-bundle support, no build system other than Meson supports that correctly.

Finally, shell-based and make-based build systems are so unreliable and ridiculously slow on Windows that the only way to actually get a reasonable dev environment is to use Meson or CMake everywhere.

**Comment by nirbheek** [comment]
> btw, any reason this is not in wrapdb ?

The difference between this project and upstream is not just that it has meson build files, or I would've added it to wrapdb already like I did for zlib.

Upstream randomly dropped 32-bit MSVC support after a rewrite, and their 64-bit MSVC support is buggy. Take a look at the commit list.

**Comment by xclaesse** [comment]
I don't think we have to build everything with msvc, but libffi is probably an exception anyway.

I guess it goes down to what's easier to maintain: cerbero or meson fork of our autotools deps. I have to admit you could be right that it's actually easier to add meson build system.

As far as I understand external-project could be good enough for cmake projects, with some tweaks.

**Comment by xclaesse** [comment]
> Upstream randomly dropped 32-bit MSVC support after a rewrite, and their 64-bit MSVC support is buggy. Take a look at the commit list.

Could be time to drop 32bits support for msvc, do we have use-case for that? Bugs with the 64bits support is annoying thought. Any chance it could be fixed upstream? Do you have link to upstream bugs?

**Comment by nirbheek** [comment]
> Could be time to drop 32bits support for msvc, do we have use-case for that? 

Yes, plenty of people ship 32-bit apps targetting Windows 7 because that works on all Windows versions.

> Bugs with the 64bits support is annoying thought. Any chance it could be fixed upstream? Do you have link to upstream bugs?

The plan is:

- [ ] win32 msvc support is currently hacked in by [reinstating old code](https://github.com/centricular/libffi/commit/faa2744c7f05a742dd972d38564d89a74cb8a802). Fix is to port the GAS syntax assembly for win32 (mingw) to Intel syntax so that it builds with MSVC, then test that it works.
- [ ] Port libffi tests to meson, and fix whatever is broken
- [ ] Setup CI using Travis and Appveyor/Azure for MSVC, MinGW, Linux, macOS, iOS, Android
- [ ] Try to upstream the meson build files and msvc fixes
- [ ] If upstreaming fails, setup CI for wrapdb and upload to wrapdb

**Comment by lazka** [comment]
@nirbheek can you upload a tarball of the release as well so it can be used in a wrap file (seems meson needs a hash and github tag tarballs aren't stable)

**Comment by nirbheek** [comment]
> can you upload a tarball of the release as well

Why not point the wrap file to a git tag?

**Comment by lazka** [comment]
> Why not point the wrap file to a git tag?

oh, right, that works too! Never mind then :)

**Pull request merged**
